version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5900:5900"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    restart: always

  frontend:
    build:
      context: ./frontend
    ports:
      - "5800:5800"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: always
